Repository woody-wordpress/woody-theme, pull requests merged in 2020-05, with the labels that each got.

#124 WIP: add new metabox linked_profil
  acf-json/group_5b0d1ed32a384.json
  acf-json/group_5b2788b48d04c.json
  acf-json/group_5c4f2efaccd2f.json
  acf-json/group_5ea2f8fe7fa8f.json
  library/classes/process/class-woody-getters.php
Labels: enhancement

#122 Feature/mini sheet tpl
  library/classes/content/class-varnish.php
  library/classes/process/class-woody-compilers.php
  library/classes/process/class-woody-getters.php
  library/classes/process/class-woody-process-tools.php
  library/classes/process/class-woody-process.php
Labels: enhancement, help wanted, question

#131 get referenced post page type
  library/classes/assets/class-enqueue-assets.php
Labels: bug
